python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 1 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 2 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 3 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 1 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 2 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 3 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 1 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 2 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 3 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 1 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 2 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 3 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 1 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 2 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 3 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 1 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 2 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 3 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 1 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 2 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 2 --inception-depth 3 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 1 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 2 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 3 --inception-depth 3 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 1 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 2 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset slap3 --kernel-size 4 --inception-depth 3 --attention-size 2 --epochs 30 --train-ratio 0.8

python train_new.py --dataset cora --kernel-size 2 --inception-depth 1 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 2 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 3 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 1 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 2 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 3 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 1 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 2 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 3 --attention-size 0 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 1 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 2 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 3 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 1 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 2 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 3 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 1 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 2 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 3 --attention-size 1 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 1 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 2 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 2 --inception-depth 3 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 1 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 2 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 3 --inception-depth 3 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 1 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 2 --attention-size 2 --epochs 30 --train-ratio 0.8
python train_new.py --dataset cora --kernel-size 4 --inception-depth 3 --attention-size 2 --epochs 30 --train-ratio 0.8
